cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _checkout: null
  _pegasus_version: '2024.10'
  _repo_dir: /tmp/tmpcrbgvy04/pegasus_template
  ai_chat_mode: openai
  ai_image_mode: none
  author_name: Chris
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: none
  description: The most amazing SaaS application the world has ever seen
  docker_setup: default
  domain_name: localhost:8000
  email: christophertskerritt@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: KW Life Care Plan Table Generator
  project_slug: kw_lcp_table_gen
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_api_auth: n
  use_api_keys: y
  use_async_example: n
  use_cloud_media_storage: n
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: n
  use_examples: y
  use_health_checks: n
  use_impersonation: y
  use_sentry: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: n
